# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: ruby:2.3

services:
  - postgres:9.5
  - redis:latest

variables:
  RAILS_ENV: test
  POSTGRES_HOST: postgres
  POSTGRES_USER: runner
  REDIS_URL: redis://redis:6379/

cache:
  paths:
    - vendor/ruby # cache gems in between builds

before_script:
  - ruby -v
  - apt-get -qq update
  - apt-get -qq -o=Dpkg::Use-Pty=0 install libicu-dev # required by charlock_holmes Gem
  - apt-get -qq -o=Dpkg::Use-Pty=0 install imagemagick # required by carrierwave Gem
  - apt-get -qq -o=Dpkg::Use-Pty=0 install postgresql-client # for psql command
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rubocop:
  script:
  - rubocop

rspec:
  script:
  - ./vendor/bin/install_phantomjs.sh
  - cp -n config/application.yml{.example,}
  - cp -n config/database.yml{.example,}
  - rake db:drop db:create db:structure:load
  - rspec

cucumber:
  script:
  - ./vendor/bin/install_phantomjs.sh
  - cp -n config/database.yml{.example,}
  - rake db:drop db:create db:structure:load
  - cucumber

integration:
  script:
  - ./vendor/bin/install_phantomjs.sh
  - cp -n config/database.yml{.example,}
  - rake db:drop db:create db:structure:load
  - ./script/ci
