# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/ruby/tags/
image: "ruby:2.2"

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - redis:latest
  - postgres:latest

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -qq update
  - apt-get -qq install libicu-dev # required by charlock_holmes Gem
  - apt-get -qq install imagemagick # required by carrierwave Gem
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rubocop:
  script:
  - rubocop

integration:
  script:
  - ./script/ci
