# See https://github.com/bbatsov/rubocop

# AllCops

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'

# Metrics

Metrics:
  Enabled: false

# Lint

Lint/AmbiguousRegexpLiteral:
  Exclude: [features/**/*] # allow "Given /^I am a cuke$/"

Lint/DefEndAlignment:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

# Style
Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AndOr:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$redis]

Style/IndentationWidth:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrivialAccessors:
  ExactNameMatch: true

Rails:
  Enabled: true

Rails/Date:
  Enabled: false # FIXME

Rails/TimeZone:
  Enabled: false # FIXME

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/ScopeArgs:
  Enabled: false # TODO: remove when Rails 4

Rails/Validation:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/UselessAssignment:
  Exclude: ["config/compass.rb", "spec/**/*"]

Lint/UselessAccessModifier:
  Enabled: false # TODO

Lint/IneffectiveAccessModifier:
  Enabled: false # TODO

Lint/UnifiedInteger:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false # TODO

Style/EachWithObject:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Next:
  Enabled: false # TODO

Style/PredicateName:
  Enabled: false # TODO

Style/RedundantSelf:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/For:
  Enabled: false # TODO

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Performance/TimesMap:
  Exclude: ["spec/**/*"]

Performance/RedundantMerge:
  Enabled: false
