Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/DefEndAlignment:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Lint/UselessAssignment:
  Exclude: ["config/compass.rb", "spec/**/*"]

Lint/LiteralInInterpolation:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/FormatParameterMismatch:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false # TODO

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  EnforcedStyle: conditionals

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false # TODO

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Next:
  Enabled: false # TODO

Style/PredicateName:
  Enabled: false # TODO

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/For:
  Enabled: false # TODO

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: true

Style/Alias:
  EnforcedStyle: prefer_alias_method

Performance/TimesMap:
  Exclude: ["spec/**/*"]

Performance/RedundantMerge:
  Enabled: false

Rails:
  Enabled: true

Rails/Date:
  Enabled: false # FIXME

Rails/TimeZone:
  Enabled: false # FIXME

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Enabled: false

# TODO: remove when Rails 4
Rails/ScopeArgs:
  Enabled: false

Rails/Validation:
  Enabled: false

