Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/DefEndAlignment:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Enabled: false

# TODO: remove when Rails 4
Rails/ScopeArgs:
  Enabled: false

Rails/Validation:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent # nice :)

Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  EnforcedStyle: conditionals

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false # TODO

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/FileName:
  Enabled: false

Style/For:
  Enabled: false # TODO

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

# Offense count: 29
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodDefParentheses:
  Enabled: false

# Offense count: 2
Style/MultilineBlockChain:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Enabled: false

# Offense count: 20
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
Style/NegatedIf:
  Enabled: false

# Offense count: 10
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/NilComparison:
  Enabled: false

# Offense count: 6
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 10

# Offense count: 5
Style/OpMethod:
  Enabled: false

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/PerlBackrefs:
  Enabled: false

# Offense count: 28
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
Style/Proc:
  Enabled: false

# Offense count: 4
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false

# Offense count: 106
# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Offense count: 5
# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false

# Offense count: 13
# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  Enabled: false

# Offense count: 59
# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Offense count: 15
# Cop supports --auto-correct.
Style/SpaceAfterColon:
  Enabled: false

# Offense count: 110
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/SpaceAfterSemicolon:
  Enabled: false

# Offense count: 50
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 226
# Cop supports --auto-correct.
Style/SpaceAroundOperators:
  Enabled: false

# Offense count: 199
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: false

# Offense count: 506
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 120
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Offense count: 269
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

# Offense count: 2757
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 21
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiteralsInInterpolation:
  Enabled: false

# Offense count: 1
Style/StructInheritance:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: false

# Offense count: 102
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: false

# Offense count: 129
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingComma:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

# Offense count: 1
Style/UnlessElse:
  Enabled: false

Rails/Date:
  Enabled: false # FIXME

Rails/TimeZone:
  Enabled: false # FIXME

Metrics/AbcSize:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Performance/Detect:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/LiteralInInterpolation:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

