Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/DefEndAlignment:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Enabled: false

# TODO: remove when Rails 4
Rails/ScopeArgs:
  Enabled: false

Rails/Validation:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent # nice :)

Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  EnforcedStyle: conditionals

Style/BracesAroundHashParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false # TODO

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/FileName:
  Enabled: false

Style/For:
  Enabled: false # TODO

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/Next:
  Enabled: false # TODO

# Offense count: 28
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
Style/Proc:
  Enabled: false

# Offense count: 4
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false

# Offense count: 106
# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Offense count: 5
# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false

# Offense count: 13
# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  Enabled: false

# Offense count: 59
# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Offense count: 15
# Cop supports --auto-correct.
Style/SpaceAfterColon:
  Enabled: false

# Offense count: 110
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
Style/SpaceAfterSemicolon:
  Enabled: false

# Offense count: 50
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

# Offense count: 226
# Cop supports --auto-correct.
Style/SpaceAroundOperators:
  Enabled: false

# Offense count: 199
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: false

# Offense count: 506
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

# Offense count: 120
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: false

# Offense count: 269
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

# Offense count: 2757
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Offense count: 21
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiteralsInInterpolation:
  Enabled: false

# Offense count: 1
Style/StructInheritance:
  Enabled: false

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: false

Style/TrailingComma:
  Enabled: false

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

# Offense count: 1
Style/UnlessElse:
  Enabled: false

Rails/Date:
  Enabled: false # FIXME

Rails/TimeZone:
  Enabled: false # FIXME

Metrics/AbcSize:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Lint/Debugger:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Performance/Detect:
  Enabled: false

Performance/ParallelAssignment:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/LiteralInInterpolation:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

