version: "3.8"

services:
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"

  postgres:
    image: postgres:9.5.22
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=buckybox
      - POSTGRES_PASSWORD=dummy
      - POSTGRES_DB=bucky_box_development
    volumes:
      - ./docker-postgres:/var/lib/postgresql/data
