# Add application configuration variables here.

# URLs
MARKETING_SITE_URL: http://www.buckybox.com/
MISSION_SITE_URL: http://www.buckybox.org/

# Emails
SUPPORT_EMAIL: Bucky Box <support@buckybox.com>
NO_REPLY_EMAIL: no-reply@buckybox.com
MAIL_SAFE: crashtestdummy@buckybox.com

# Delayed::Job
DELAYED_JOB_PRIORITY_HIGH: 0
DELAYED_JOB_PRIORITY_LOW:  50

# Vero
VERO_API_KEY: '8029577e167a4f55a6262d8eff46ea0a445d21b0'
VERO_SECRET: '76ab27793509fe90650d66de91841d3e41dafefe'

# Email headers
X_MAILER: 'Bucky Box Mailer (1.0.0) www.buckybox.com'

# Environment-dependant configuration
development:
  HOST: buckybox.dev
  PORT: 3000

test:
  HOST: buckybox.dev
  PORT: 3000

staging:
  HOST: staging.buckybox.com
  MANDRILL_PASSWORD: "B44y6SC4tEhaQMLKMfIvdA"
  MANDRILL_EMAIL: "sysadmins@buckybox.com"

production:
  HOST: my.buckybox.com
  USERCYCLE_API_KEY: '8c7ad3ac4a5e8fe80258662dd42d961f99f4e703'
  MANDRILL_PASSWORD: "Tw231I6mhCW5ZJTs2KG8NA"
  MANDRILL_EMAIL: "sysadmins+prod@buckybox.com"

