# Add application configuration variables here.

# URLs
MARKETING_SITE_URL: http://www.buckybox.com/
MISSION_SITE_URL: http://www.buckybox.org/

# Emails
SUPPORT_EMAIL: support@buckybox.com
NO_REPLY_EMAIL: no-reply@buckybox.com
SIGNUPS_EMAIL: signups@buckybox.com
SYSALERTS_EMAIL: sysalerts@buckybox.com
MAIL_SAFE: crashtestdummy@buckybox.com
TEAM_EMAILS: will@buckybox.com, sam@buckybox.com, jordan@buckybox.com, samson@buckybox.com, ced@buckybox.com

# Airbrake
AIRBRAKE_HOST: "api.airbrake.io"
AIRBRAKE_API_KEY: "e4145e68bb8f78c4380f502c3cddc339"

# GMail SMTP
GMAIL_SMTP_HOST: smtp.gmail.com
GMAIL_SMTP_PORT: 587
GMAIL_SMTP_USER_NAME: support@buckybox.com
GMAIL_SMTP_PASSWORD: betathanever
GMAIL_SMTP_AUTHENTICATION: plain
GMAIL_SMTP_ENABLE_STARTTLS_AUTO: true

# Delayed::Job
DELAYED_JOB_PRIORITY_HIGH: 0
DELAYED_JOB_PRIORITY_LOW:  50

# Delayed::Job Web interface
DELAYED_JOB_USERNAME: "bg_job_master"
DELAYED_JOB_PASSWORD: "What's in the queue?"

# Intercom
INTERCOM_APP_ID: "b3e72f90ddcc230dea36a8e35ec7e4dd65860b61"
INTERCOM_API_KEY: "229897e267e10c51092f04ef67bac6813cb4c078"
INTERCOM_API_SECRET: "prVxueBF1rB3TaRdjPOUfy-_Y8uuFPr62VCOLxbs"

# Email headers
X_MAILER: 'Bucky Box Mailer (1.0.0) www.buckybox.com'

# Environment-dependant configuration
development:
  HOST: buckybox.dev
  PORT: 3000

test:
  HOST: buckybox.dev
  PORT: 3000

staging:
  HOST: staging.buckybox.com
  MANDRILL_PASSWORD: "B44y6SC4tEhaQMLKMfIvdA"
  MANDRILL_EMAIL: "sysadmins@buckybox.com"

production:
  HOST: my.buckybox.com
  USERCYCLE_API_KEY: '8c7ad3ac4a5e8fe80258662dd42d961f99f4e703'
  MANDRILL_PASSWORD: "Tw231I6mhCW5ZJTs2KG8NA"
  MANDRILL_EMAIL: "sysadmins+prod@buckybox.com"

