# Add application configuration variables here.

# URLs
MARKETING_SITE_URL: http://www.buckybox.com/
MISSION_SITE_URL: http://www.buckybox.org/

# Emails
SUPPORT_EMAIL: Bucky Box <support@buckybox.com>
NO_REPLY_EMAIL: no-reply@buckybox.com
MAIL_SAFE: crashtestdummy@buckybox.com

# Delayed::Job
DELAYED_JOB_PRIORITY_HIGH: 0
DELAYED_JOB_PRIORITY_LOW:  50

# Usercycle
USERCYCLE_API_KEY: '624a19c076449cb71c750ab7ef5909de7f488dc1'
USERCYCLE_API_URL: 'https://api.usercycle.com/api/v1'

# Environment-dependant configuration
development:
  HOST: buckybox.dev
  PORT: 3000

test:
  HOST: buckybox.dev
  PORT: 3000

staging:
  HOST: staging.buckybox.com
  POSTMARK_API_KEY: 3c3bf3ae-b9a4-4c9a-b850-bc6528fb12bc

production:
  HOST: my.buckybox.com
  POSTMARK_API_KEY: 63583ad4-c990-4ccb-a7db-afcc85d9070a

