# Add application configuration variables here.

# URLs
MARKETING_SITE_URL: http://www.buckybox.com/
MISSION_SITE_URL: http://www.buckybox.org/

# Emails
SUPPORT_EMAIL: Bucky Box <support@buckybox.com>
NO_REPLY_EMAIL: no-reply@buckybox.com
MAIL_SAFE: crashtestdummy@buckybox.com

# Delayed::Job
DELAYED_JOB_PRIORITY_HIGH: 0
DELAYED_JOB_PRIORITY_LOW:  50

# Usercycle
USERCYCLE_API_KEY: '624a19c076449cb71c750ab7ef5909de7f488dc1'
USERCYCLE_API_URL: 'https://api.usercycle.com/api/v1'

#Mandrillapp
MANDRILL_PASSWORD: "B44y6SC4tEhaQMLKMfIvdA"
MANDRILL_EMAIL: "sysadmins@buckybox.com"

# Environment-dependant configuration
development:
  HOST: buckybox.dev
  PORT: 3000

test:
  HOST: buckybox.dev
  PORT: 3000

staging:
  HOST: staging.buckybox.com

production:
  HOST: my.buckybox.com
  USERCYCLE_API_KEY: '8c7ad3ac4a5e8fe80258662dd42d961f99f4e703'

