---
# The Skylight ID for the application.
application: TfqJ8V0Hv4OX

# The authentication token for the application.
authentication: pS8822qw6qt8EZKzco5NO9NUOWgaV6CLBdPrzZG9S4RhcHBsaWNhdGlvbl9pZHM9VGZxSjhWMEh2NE9YJnJvbGU9YWdlbnQ=
